/**
 * Represents an error that could occur in the game Labyrinth.
 */
export class LabyrinthError extends Error {
    readonly message: string;
    readonly code: ErrorCode;
    constructor(params: { message: string, code: ErrorCode }) {
        super();
        this.message = params.message;
        this.code = params.code;
    }
}

/**
 * Represents an error code that corresponds to a specific error.
 */
export enum ErrorCode {
    // Board
    BOARD_IRREGULAR_DIMENSIONS = 'BOARD_IRREGULAR_DIMENSIONS',
    BOARD_MOVE_INVALID_SELECTION = 'BOARD_MOVE_INVALID_SELECTION',
    BOARD_MOVE_OUT_OF_RANGE = 'BOARD_MOVE_OUT_OF_RANGE',
    BOARD_INVALID_COORDINATE = 'BOARD_INVALID_COORDINATE',
    GAME_STATE_ACTIVE_PLAYER_UNDEFINED = 'GAME_STATE_ACTIVE_PLAYER_UNDEFINED',
    GAME_STATE_UNKNOWN_PLAYER = 'GAME_STATE_UNKNOWN_PLAYER',
    BOARD_ACTION_UNDOES_PREVIOUS = 'BOARD_ACTION_UNDOES_PREVIOUS',

    // Game state
    NO_PLAYERS = 'NO_PLAYERS',
    PLAYER_MOVE_SAME_POSITION = 'PLAYER_MOVE_SAME_POSITION',
    PLAYER_MOVE_OUT_OF_RANGE = 'PLAYER_MOVE_OUT_OF_RANGE',
    PLAYER_CANNOT_MOVE_TO_TILE = 'PLAYER_CANNOT_MOVE_TO_TILE',
    PLAYER_WITH_COLOR_NOT_FOUND = 'PLAYER_WITH_COLOR_NOT_FOUND',
    INVALID_COLOR = 'INVALID_COLOR',
    AVATAR_COLORS_NOT_UNIQUE = 'AVATAR_COLORS_NOT_UNIQUE',
    AVATAR_HOMES_NOT_UNIQUE = 'AVATAR_HOMES_NOT_HOME',
    COORDINATE_ELEMENT_NOT_INTEGER = 'COORDINATE_ELEMENT_NOT_INTEGER',
    TREASURES_NOT_UNIQUE = 'TREASURES_NOT_UNIQUE',
    INVALID_TILE_ROTATIONS = 'INVALID_TILE_ROTATIONS',
    CANNOT_SIMULATE_NEXT_STATE = 'CANNOT_SIMULATE_NEXT_STATE',
    CANNOT_REMOVE_PLAYER = 'CANNOT_REMOVE_PLAYER',
    AVATAR_OUT_OF_RANGE = 'AVATAR_OUT_OF_RANGE',

    // Player
    TREASURE_LOCATION_NOT_FOUND = 'TREASURE_LOCATION_NOT_FOUND',
    PLAYER_INFO_NOT_FOUND = 'PLAYER_INFO_NOT_FOUND',
    PLAYER_NOT_SETUP = 'PLAYER_NOT_SETUP',

    // Referee
    GAME_ALREADY_STARTED = 'GAME_ALREADY_STARTED',
    NAME_ALREADY_TAKEN = 'NAME_ALREADY_TAKEN',
    PLAYER_COLORS_DO_NOT_MATCH = 'PLAYER_COLORS_DO_NOT_MATCH',
    PLAYER_AVATAR_NOT_FOUND = 'PLAYER_AVATAR_NOT_FOUND',
    AVATAR_PLAYER_MAP_MISMATCH = 'AVATAR_PLAYER_MAP_MISMATCH',
    BOARD_SIZE_MISMATCH = 'BOARD_SIZE_MISMATCH',
    BOARD_SIZE_INVALID = 'BOARD_SIZE_INVALID',
    NO_IMMOVABLE_TILES = 'NO_IMMOVABLE_TILES',

    // Network Player
    PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED',
    //Stream Player
    STREAM_CLOSED = 'STREAM_CLOSED',

    // Deprecated
    GAMESTATE_UNDEFINED = 'GAMESTATE_UNDEFINED',
    INVALID_UUID_FORMAT = 'INVALID_UUID_FORMAT',

    TOO_MANY_PLAYERS = 'TOO_MANY_PLAYERS'
}
