#!/bin/bash
set -e

for i in {0..4}
do
  ../../executeTest ../xbad2 ../Tests/$i
  echo
done

for input_file in ../../Maze/integration_tests/TestInputs/8/*/*-in.json
do
  # Removes the shortest match from / to the end of the string (ie. the filename)
  dir=${input_file%/*}
  # Removes the longest match from .. to / (ie. the directory part of the path)
  filename=${input_file##..*/}
  # Given the filename, only keep everything before the - (ie. the number of the text)
  test_number=${filename%-*}
  
  ../../executeTest ../xbad2 $dir/$test_number
  echo
done